#!/bin/sh
CC=gcc
SRC=lucas_num.c

$CC -Wall -g $SRC && (
	cat input | ./a.exe \
	# strip carriage returns - just in case
	| tr -d "\r" \
	> actual &&
	diff -u actual exp && echo "pass!" || (
		echo "failed!";
		cat actual;
	)
)
